//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rockmelon.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int GameId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
